spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: jt-group-5
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
          spring.json.trusted.packages: "com.kafak.consumer.dto"
          spring.json.value.default.type: com.kafak.consumer.dto.Customer
          spring.json.use.type.headers: false